@startmindmap
* Безопасность данных
** Публичные данные
*** Общая информация о компании
**** Риск: Искажение данных (значительный)
***** Пояснение: Может подорвать доверие клиентов
** Внутренние данные
*** Операционная информация
**** Риск: Потеря данных (значительный)
***** Пояснение: Утрата документации повлияет на эффективность работы
**** Риск: Искажение данных (значительный)
***** Пояснение: Ошибочные данные приводят к сбоям в операционной деятельности
** Конфиденциальные данные
*** Персональные данные клиентов
**** Риск: Утечка данных (критический)
***** Пояснение: Утечка данных может вызвать юридические и репутационные последствия
**** Риск: Искажение данных (критический)
***** Пояснение: Неправильные данные нарушают процессы обслуживания клиентов
**** Риск: Некачественные данные (значительный)
***** Пояснение: Трудности в принятии решений по продажам
** Секретные данные
*** Доступ к финансовой информации
**** Риск: Утечка данных (критический)
***** Пояснение: Могут возникнуть финансовые и стратегические потери
**** Риск: Потеря данных (критический)
***** Пояснение: Потеря финансовых данных угрожает устойчивости компании
**** Риск: Искажение данных (критический)
***** Пояснение: Ошибочные данные ведут к принятию неверных решений
@endmindmap